Set-StrictMode -Version 2.0
$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "server_config.ps1")

function Assert-Administrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    $isAdmin = $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        throw "Administrator privileges are required."
    }
}

function Ensure-ServerDirectories {
    foreach ($path in @($LogDirectory, $BackupDirectory, $RuntimeDirectory)) {
        if (-not (Test-Path -LiteralPath $path)) {
            New-Item -ItemType Directory -Path $path -Force | Out-Null
        }
    }
}

function Wait-ServerPort {
    param([int]$Port = $ServerPort, [int]$TimeoutSeconds = 30)

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    do {
        try {
            if (Test-NetConnection -ComputerName "127.0.0.1" -Port $Port -InformationLevel Quiet -WarningAction SilentlyContinue) {
                return $true
            }
        } catch {
        }
        Start-Sleep -Milliseconds 500
    } while ((Get-Date) -lt $deadline)

    return $false
}

function Stop-ServerPortListeners {
    param([int]$Port = $ServerPort)

    $pids = New-Object System.Collections.Generic.HashSet[int]
    try {
        foreach ($connection in Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction Stop) {
            [void]$pids.Add([int]$connection.OwningProcess)
        }
    } catch {
    }

    foreach ($line in (netstat -ano | Select-String ":$Port\s" | Select-String "LISTENING")) {
        $value = ($line -split "\s+")[-1]
        if ($value -match "^\d+$") {
            [void]$pids.Add([int]$value)
        }
    }

    foreach ($processId in $pids) {
        if (Get-Process -Id $processId -ErrorAction SilentlyContinue) {
            & taskkill.exe /F /T /PID $processId 2>&1 | Out-Null
        }
    }
}

function Resolve-CertificatePair {
    param([string]$RequestedCert = "", [string]$RequestedKey = "")

    if ($RequestedCert -and -not (Test-Path -LiteralPath $RequestedCert -PathType Leaf)) {
        throw "Certificate file not found: $RequestedCert"
    }
    if ($RequestedKey -and -not (Test-Path -LiteralPath $RequestedKey -PathType Leaf)) {
        throw "Private key file not found: $RequestedKey"
    }
    if ($RequestedCert -and $RequestedKey) {
        return [PSCustomObject]@{ Cert = (Resolve-Path $RequestedCert).Path; Key = (Resolve-Path $RequestedKey).Path }
    }

    if (-not (Test-Path -LiteralPath $CertDirectory -PathType Container)) {
        throw "Certificate directory not found: $CertDirectory"
    }

    $allFiles = @(Get-ChildItem -LiteralPath $CertDirectory -Recurse -File)
    $cert = $null
    $key = $null

    if ($RequestedCert) {
        $cert = Get-Item -LiteralPath $RequestedCert
    } else {
        foreach ($name in @("fullchain.pem", "cert.pem", "certificate.pem", "server.crt", "server.cer")) {
            $match = @($allFiles | Where-Object { $_.Name -ieq $name })
            if ($match.Count -eq 1) { $cert = $match[0]; break }
        }
        if ($null -eq $cert) {
            $fallback = @($allFiles | Where-Object { $_.Extension -in @(".crt", ".cer", ".pem") -and $_.Name -notmatch "(?i)(privkey|key)" })
            if ($fallback.Count -eq 1) { $cert = $fallback[0] }
            elseif ($fallback.Count -gt 1) { throw "Multiple certificate candidates found. Re-run server_install.ps1 with -CertFile." }
        }
    }

    if ($RequestedKey) {
        $key = Get-Item -LiteralPath $RequestedKey
    } else {
        foreach ($name in @("privkey.pem", "key.pem", "server.key")) {
            $match = @($allFiles | Where-Object { $_.Name -ieq $name })
            if ($match.Count -eq 1) { $key = $match[0]; break }
        }
        if ($null -eq $key) {
            $fallback = @($allFiles | Where-Object { $_.Extension -eq ".key" -or $_.Name -match "(?i)(privkey|key).*\.pem$" })
            if ($fallback.Count -eq 1) { $key = $fallback[0] }
            elseif ($fallback.Count -gt 1) { throw "Multiple private-key candidates found. Re-run server_install.ps1 with -KeyFile." }
        }
    }

    if ($null -eq $cert) { throw "No certificate file found in $CertDirectory" }
    if ($null -eq $key) { throw "No private-key file found in $CertDirectory" }

    return [PSCustomObject]@{ Cert = $cert.FullName; Key = $key.FullName }
}

function Write-LocalServerConfig {
    param([Parameter(Mandatory = $true)][string]$ResolvedCert, [Parameter(Mandatory = $true)][string]$ResolvedKey, [int]$Port = 7777)

    $localPath = Join-Path $PSScriptRoot "server.local.ps1"
    $certLiteral = $ResolvedCert.Replace("'", "''")
    $keyLiteral = $ResolvedKey.Replace("'", "''")
    $content = @(
        "# Generated by server_install.ps1. Do not commit this file.",
        ('$ServerPort = {0}' -f $Port),
        ('$FirewallRuleName = "Estimate AI {0}"' -f $Port),
        ('$CertFile = ''{0}''' -f $certLiteral),
        ('$KeyFile = ''{0}''' -f $keyLiteral)
    )
    Set-Content -LiteralPath $localPath -Value $content -Encoding ASCII
}

function Test-DatabaseIntegrity {
    if (-not (Test-Path -LiteralPath $DatabasePath -PathType Leaf)) { throw "Database file not found: $DatabasePath" }
    if (-not (Test-Path -LiteralPath $VenvPython -PathType Leaf)) { throw "Virtualenv Python not found: $VenvPython" }

    $env:ESTIMATE_AI_CHECK_DB = $DatabasePath
    try {
        $result = & $VenvPython -c "import os,sqlite3; c=sqlite3.connect(os.environ['ESTIMATE_AI_CHECK_DB']); print(c.execute('PRAGMA integrity_check').fetchone()[0]); c.close()"
        if (($result | Select-Object -Last 1).Trim() -ne "ok") { throw "SQLite integrity_check failed: $result" }
    } finally {
        Remove-Item Env:ESTIMATE_AI_CHECK_DB -ErrorAction SilentlyContinue
    }
}

function Backup-Database {
    param([string]$Label = "backup")

    Ensure-ServerDirectories
    if (-not (Test-Path -LiteralPath $DatabasePath -PathType Leaf)) { return $null }
    if (-not (Test-Path -LiteralPath $VenvPython -PathType Leaf)) { throw "Virtualenv Python not found: $VenvPython" }

    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $destination = Join-Path $BackupDirectory ("estimate_ai-{0}-{1}.db" -f $Label, $stamp)
    $env:ESTIMATE_AI_BACKUP_SOURCE = $DatabasePath
    $env:ESTIMATE_AI_BACKUP_DEST = $destination
    try {
        & $VenvPython -c "import os,sqlite3; s=sqlite3.connect(os.environ['ESTIMATE_AI_BACKUP_SOURCE']); d=sqlite3.connect(os.environ['ESTIMATE_AI_BACKUP_DEST']); s.backup(d); d.close(); s.close()"
        if ($LASTEXITCODE -ne 0) { throw "SQLite backup failed." }
    } finally {
        Remove-Item Env:ESTIMATE_AI_BACKUP_SOURCE -ErrorAction SilentlyContinue
        Remove-Item Env:ESTIMATE_AI_BACKUP_DEST -ErrorAction SilentlyContinue
    }
    return $destination
}
