"""SQLite persistence for catalog, import log, and admin config."""

from core.storage.connection import connect, default_database_path, init_database
from core.storage.catalog import (
    filename_is_processed,
    filename_is_final_for_preview,
    imported_file_exists_for_region,
    import_catalog_from_excel,
    import_legacy_file_log,
    list_catalog_rows,
    list_catalog_sources,
    list_imported_files,
    normalize_import_filename,
    record_imported_file,
    count_catalog_rows,
)
from core.storage.rules import (
    import_rules_from_workbook,
    list_name_exclusion_rules,
    list_task_color_entries,
    replace_name_exclusion_rules,
    replace_task_color_entries,
    set_name_exclusion_rule_enabled,
    set_task_color_enabled,
    upsert_name_exclusion_rule,
    upsert_task_color_entry,
)
from core.storage.risk_log import (
    FlaggedRiskSnapshot,
    PriceRiskLogEntry,
    approve_risk,
    database_is_available,
    list_gesn_exceptions,
    list_price_risks,
    get_price_risk,
    load_gesn_exceptions,
    persist_flagged_risks,
    save_gesn_exception,
    upsert_open_risk,
)

__all__ = [
    "connect",
    "default_database_path",
    "init_database",
    "filename_is_processed",
    "filename_is_final_for_preview",
    "imported_file_exists_for_region",
    "import_catalog_from_excel",
    "import_legacy_file_log",
    "list_catalog_rows",
    "list_catalog_sources",
    "list_imported_files",
    "normalize_import_filename",
    "record_imported_file",
    "count_catalog_rows",
    "import_rules_from_workbook",
    "list_name_exclusion_rules",
    "list_task_color_entries",
    "replace_name_exclusion_rules",
    "replace_task_color_entries",
    "set_name_exclusion_rule_enabled",
    "set_task_color_enabled",
    "upsert_name_exclusion_rule",
    "upsert_task_color_entry",
    "FlaggedRiskSnapshot",
    "PriceRiskLogEntry",
    "approve_risk",
    "database_is_available",
    "list_gesn_exceptions",
    "list_price_risks",
    "get_price_risk",
    "load_gesn_exceptions",
    "persist_flagged_risks",
    "save_gesn_exception",
    "upsert_open_risk",
]
