"""Persistence for the TKP (tender winner) catalog.

Delta-import model: `import_tkp_catalog_workbook` can be pointed at the same
aggregate `Каталог_ТКПшек*.xlsm` workbook every time it is regenerated by
the KL20 CatalogBuilder macro (which re-scans the whole watched folder, not
just new files). A source file is only re-imported when it is new or its
`ModifiedDate` changed; unchanged files are skipped, keeping repeated
imports of the same workbook cheap and idempotent -- the RNMC import
(`core/storage/catalog.py`) uses the same dedup shape, filename-keyed there
since RNMC has no reliable modified-date signal.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from pathlib import Path

from core.tkp_ingest import TkpItem, TkpSourceFile, parse_tkp_catalog_workbook


@dataclass(frozen=True)
class TkpImportResult:
    """Summary of one import run against the TKP catalog tables."""

    files_seen: int
    files_imported: int
    files_updated: int
    files_skipped: int
    items_imported: int


@dataclass(frozen=True)
class TkpSourceRecord:
    """A stored `tkp_sources` row, as shown in the admin UI."""

    id: int
    run_id: str
    file_name: str
    file_path: str
    modified_date: str
    parse_status: str
    parse_message: str
    task_no: str
    customer: str
    procedure_name: str
    winner_name: str
    winner_total_no_vat: float | None
    item_count: int
    imported_at: str


@dataclass(frozen=True)
class TkpItemRecord:
    """A stored `tkp_items` row, joined with its source file name."""

    id: int
    source_id: int
    source_file_name: str
    item_name: str
    unit: str
    qty: float | None
    winner_unit_price_no_vat: float | None
    winner_name: str
    task_no: str
    procedure_name: str


def import_tkp_catalog_workbook(
    connection: sqlite3.Connection,
    workbook_path: str | Path,
) -> TkpImportResult:
    """Parse `workbook_path` and insert any source files not yet imported."""
    result = parse_tkp_catalog_workbook(workbook_path)

    items_by_file_path: dict[str, list[TkpItem]] = {}
    for item in result.items:
        items_by_file_path.setdefault(item.file_path, []).append(item)

    files_imported = 0
    files_updated = 0
    files_skipped = 0
    items_imported = 0

    for source_file in result.files:
        outcome = _upsert_source_file(
            connection,
            source_file,
            items_by_file_path.get(source_file.file_path, []),
        )
        if outcome == "imported":
            files_imported += 1
        elif outcome == "updated":
            files_updated += 1
        else:
            files_skipped += 1

    connection.commit()

    items_imported = connection.execute(
        "SELECT COUNT(*) AS n FROM tkp_items"
    ).fetchone()["n"]

    return TkpImportResult(
        files_seen=len(result.files),
        files_imported=files_imported,
        files_updated=files_updated,
        files_skipped=files_skipped,
        items_imported=items_imported,
    )


def _upsert_source_file(
    connection: sqlite3.Connection,
    source_file: TkpSourceFile,
    items: list[TkpItem],
) -> str:
    """Insert, replace, or skip one source file. Returns imported/updated/skipped."""
    modified_key = _iso(source_file.modified_date)
    existing = connection.execute(
        "SELECT id, modified_date FROM tkp_sources WHERE file_name = ? AND modified_date = ?",
        (source_file.file_name, modified_key),
    ).fetchone()

    if existing is not None:
        return "skipped"

    # A file with the same name but a different (or previously blank)
    # modified_date is treated as an updated version: replace its old rows
    # so stale items are never left mixed in with the refreshed ones.
    stale = connection.execute(
        "SELECT id FROM tkp_sources WHERE file_name = ?",
        (source_file.file_name,),
    ).fetchall()
    was_update = len(stale) > 0
    for row in stale:
        connection.execute("DELETE FROM tkp_sources WHERE id = ?", (int(row["id"]),))

    cursor = connection.execute(
        """
        INSERT INTO tkp_sources (
            run_id, file_path, file_name, modified_date, sheet_name,
            parse_status, parse_message, task_no, request_date, customer,
            general_contractor, procedure_name, winner_name, winner_inn,
            winner_uin, winner_total_no_vat, winner_total_vat,
            rnmc_total_no_vat, item_count
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            source_file.run_id,
            source_file.file_path,
            source_file.file_name,
            modified_key,
            source_file.sheet_name,
            source_file.parse_status,
            source_file.parse_message,
            source_file.task_no,
            _iso(source_file.request_date),
            source_file.customer,
            source_file.general_contractor,
            source_file.procedure_name,
            source_file.winner_name,
            source_file.winner_inn,
            source_file.winner_uin,
            source_file.winner_total_no_vat,
            source_file.winner_total_vat,
            source_file.rnmc_total_no_vat,
            len(items),
        ),
    )
    source_id = int(cursor.lastrowid)

    for item in items:
        connection.execute(
            """
            INSERT INTO tkp_items (
                source_id, source_row, section_code, section_name,
                subsection_name, item_code, item_name, unit, qty,
                rnmc_unit_price_no_vat, winner_unit_price_no_vat,
                winner_line_total_no_vat, winner_name, winner_inn,
                winner_uin, task_no, request_date, customer,
                general_contractor, procedure_name
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                source_id,
                item.source_row,
                item.section_code,
                item.section_name,
                item.subsection_name,
                item.item_code,
                item.item_name,
                item.unit,
                item.qty,
                item.rnmc_unit_price_no_vat,
                item.winner_unit_price_no_vat,
                item.winner_line_total_no_vat,
                item.winner_name,
                item.winner_inn,
                item.winner_uin,
                item.task_no,
                _iso(item.request_date),
                item.customer,
                item.general_contractor,
                item.procedure_name,
            ),
        )

    return "updated" if was_update else "imported"


def list_tkp_sources(connection: sqlite3.Connection) -> list[TkpSourceRecord]:
    rows = connection.execute(
        """
        SELECT id, run_id, file_name, file_path, modified_date, parse_status,
               parse_message, task_no, customer, procedure_name, winner_name,
               winner_total_no_vat, item_count, imported_at
        FROM tkp_sources
        ORDER BY imported_at DESC, id DESC
        """
    ).fetchall()
    return [
        TkpSourceRecord(
            id=int(row["id"]),
            run_id=str(row["run_id"]),
            file_name=str(row["file_name"]),
            file_path=str(row["file_path"]),
            modified_date=str(row["modified_date"]),
            parse_status=str(row["parse_status"]),
            parse_message=str(row["parse_message"]),
            task_no=str(row["task_no"]),
            customer=str(row["customer"]),
            procedure_name=str(row["procedure_name"]),
            winner_name=str(row["winner_name"]),
            winner_total_no_vat=row["winner_total_no_vat"],
            item_count=int(row["item_count"]),
            imported_at=str(row["imported_at"]),
        )
        for row in rows
    ]


def count_tkp_items(connection: sqlite3.Connection) -> int:
    return int(connection.execute("SELECT COUNT(*) AS n FROM tkp_items").fetchone()["n"])


def list_tkp_items(
    connection: sqlite3.Connection,
    *,
    limit: int = 200,
    offset: int = 0,
) -> list[TkpItemRecord]:
    rows = connection.execute(
        """
        SELECT tkp_items.id, tkp_items.source_id, tkp_sources.file_name AS source_file_name,
               tkp_items.item_name, tkp_items.unit, tkp_items.qty,
               tkp_items.winner_unit_price_no_vat, tkp_items.winner_name,
               tkp_items.task_no, tkp_items.procedure_name
        FROM tkp_items
        JOIN tkp_sources ON tkp_sources.id = tkp_items.source_id
        ORDER BY tkp_items.id
        LIMIT ? OFFSET ?
        """,
        (limit, offset),
    ).fetchall()
    return [
        TkpItemRecord(
            id=int(row["id"]),
            source_id=int(row["source_id"]),
            source_file_name=str(row["source_file_name"]),
            item_name=str(row["item_name"]),
            unit=str(row["unit"]),
            qty=row["qty"],
            winner_unit_price_no_vat=row["winner_unit_price_no_vat"],
            winner_name=str(row["winner_name"]),
            task_no=str(row["task_no"]),
            procedure_name=str(row["procedure_name"]),
        )
        for row in rows
    ]


def _iso(value) -> str:
    if value is None:
        return ""
    return value.isoformat()
